apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzero-file
  labels:
    app.kubernetes.io/name: "srm-test"
    app.kubernetes.io/instance: "srm-test"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "srm-test"
      app.kubernetes.io/instance: "srm-test"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "srm-test"
        app.kubernetes.io/instance: "srm-test"
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
        - name: srm-test
          image: "029937289256.dkr.ecr.ap-northeast-1.amazonaws.com/srm-test:0.0.1"
          imagePullPolicy: Always
          env:
          - name: "EUREKA_INSTANCE_PREFER_IP_ADDRESS"
            value: "true"
          envFrom:
          - configMapRef:
              name: srm-test-cm
          ports:
            - name: http
              containerPort: 8110
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8111
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              memory: 1024Mi
              cpu: 2000m
            requests:
              memory: 800Mi
              cpu: 75m