apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: default
spec:
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - image: <IMAGE_NAME>:<IMAGE_TAG>
          imagePullPolicy: IfNotPresent
          name: <APP_NAME>